services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant_db
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./qdrant_storage:/qdrant/storage
    restart: always

  web_app:
    build: .
    container_name: lky_chatbot
    ports:
      - "8501:8501"
    environment:
      # Tell the app to connect to the Qdrant container, not the local folder
      - QDRANT_URL=http://qdrant:6333
      # host.docker.internal allows the Docker container to talk to Ollama on your Windows host
      - OLLAMA_URL=http://host.docker.internal:11434/api/chat
    depends_on:
      - qdrant
    restart: always
